# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'xsport' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xsport

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
  'Core',
  'ART',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTLinkingIOS',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'DevSupport',
  'CxxBridge',
  ]

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  swift5 = ['Charts', 'SwiftyJSON']

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if swift5.include?(target.name)
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
  end

end
