import React, { Component } from "react";
import { View, TouchableOpacity, Image, ScrollView } from "react-native";
import { SafeAreaView } from "react-navigation";
import { SideMenu, Text, Button } from "@AppComponents";
import { Icons, Colors } from "@AppTheme";
import { Input, CheckBox } from "react-native-elements";
import styles from "./styles";

export default class TwoFASetPhoneNumberScreen extends Component {
  state = {
    value: "+27",
    dontAskForCode: true
  };

  onSelect = value => {
    this.setState({ value });
  };

  goBack = () => {
    this.props.navigation.goBack();
  };

  handleCheck = () => {
    this.setState(state => ({ dontAskForCode: !state.dontAskForCode }));
  };

  render() {
    const options = [
      { value: "+27", label: "+27 RSA" },
      { value: "+234", label: "+234 NGA" }
    ];

    return (
      <SafeAreaView style={styles.container}>
        <SideMenu title="security">
          <ScrollView
            style={styles.content}
            contentContainerStyle={{ alignItems: "center" }}
          >
            <View style={styles.header}>
              <TouchableOpacity onPress={this.goBack}>
                <Image source={Icons.arrowLeftWhite} resizeMode="contain" />
              </TouchableOpacity>
              <Text style={styles.headerTitle}>Two-factor auth.</Text>
            </View>

            <View style={styles.infoBox}>
              <View style={styles.row}>
                <Image
                  source={Icons.question}
                  resizeMode="contain"
                  style={styles.infoIcon}
                />
                <Text style={styles.infoTitle}>Enter verification code</Text>
              </View>
              <Text style={styles.infoBody}>
                Enter the verification code generated by your cell phone ending
                in +27 XXX XXX XXXX. You can use the Adroid Auth or Google
                authenticator app on your phone.
              </Text>
            </View>

            <View style={styles.inputBox}>
              <Text style={styles.label}>Enter Code</Text>
              <Input
                secureTextEntry
                textContentType="password"
                inputStyle={styles.input}
                inputContainerStyle={styles.inputContainer}
                leftIcon={<Image source={Icons.question} />}
              />

              <Button
                title="VERIFY"
                style={styles.button}
                textStyle={styles.buttonText}
              />

              <View style={styles.checkContainer}>
                <CheckBox
                  size={19}
                  checked={this.state.dontAskForCode}
                  uncheckedColor={Colors.malachite}
                  checkedColor={Colors.malachite}
                  onPress={this.handleCheck}
                />
                <Text style={styles.checkBoxInfo}>
                  Don’t ask me for the code again for 30 days when I use this
                  device.
                </Text>
              </View>

              <View
                style={[
                  styles.row,
                  { justifyContent: "space-between", marginTop: 20 }
                ]}
              >
                <View style={[styles.row, { flex: 1 }]}>
                  <Image
                    source={Icons.question}
                    resizeMode="contain"
                    style={styles.helpIcon}
                  />
                  <Text style={styles.helpText}>Resend CODE</Text>
                </View>
                <View style={styles.row}>
                  <Image
                    source={Icons.question}
                    resizeMode="contain"
                    style={styles.helpIcon}
                  />
                  <Text style={styles.helpText}>Help/Support</Text>
                </View>
              </View>
            </View>
          </ScrollView>
        </SideMenu>
      </SafeAreaView>
    );
  }
}
